# Generated by Django 2.1.15 on 2020-06-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('SubCategory', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('HashTag', models.CharField(max_length=100)),
                ('ExpiringInHours', models.CharField(max_length=100)),
                ('BudgetPriceInRs', models.CharField(max_length=100)),
                ('DateCreated', models.DateField()),
                ('DateUpdated', models.DateField()),
            ],
        ),
    ]
