# Generated by Django 2.1.15 on 2020-06-28 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='AddressLine1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='AddressLine2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='City',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='PinCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='State',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='DateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
