# Generated by Django 2.1.15 on 2020-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0003_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='TicketId',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
