# Generated by Django 2.1.15 on 2020-06-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0005_auto_20200630_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='Auth_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
