# Generated by Django 2.1.15 on 2020-06-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0006_ticketdetails_auth_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='Auth_key',
            new_name='Auth_Key',
        ),
    ]
