# Generated by Django 2.1.15 on 2020-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0007_auto_20200701_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='Auth_key',
            new_name='Auth_Key',
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='Scope',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
