# Generated by Django 2.1.15 on 2020-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0008_auto_20200704_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='AddressLine1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='AddressLine2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='BudgetPriceInRs',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='City',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='ExpiringInHours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='HashTag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='PinCode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='Scope',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='State',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='SubCategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
