# Generated by Django 2.1.15 on 2020-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0009_auto_20200704_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='Scope',
            field=models.CharField(blank=True, default='Local', max_length=100),
        ),
    ]
