# Generated by Django 2.1.15 on 2020-07-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0011_auto_20200704_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='TicketDescription',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
