# Generated by Django 2.1.15 on 2020-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0013_remove_ticketdetails_auth_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='AddressLine1',
            new_name='addressline1',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='AddressLine2',
            new_name='budget_in_rs',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='BudgetPriceInRs',
            new_name='expiring_in_hours',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='DateCreated',
            new_name='datecreated',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='DateUpdated',
            new_name='dateupdated',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='ExpiringInHours',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='Scope',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='TicketId',
            new_name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticketdetails',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='ticketdetails',
            name='TicketDescription',
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='ticket_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='ticketdetails',
            table='ticket_details',
        ),
    ]
