# Generated by Django 2.1.15 on 2020-07-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0014_auto_20200709_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='HashTag',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='PinCode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='State',
            new_name='state',
        ),
    ]
