# Generated by Django 2.1.15 on 2020-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0015_auto_20200709_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
