# Generated by Django 2.1.15 on 2020-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0016_ticketdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
    ]
