# Generated by Django 2.1.15 on 2020-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0017_ticketdetails_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='addressline1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='country',
            field=models.CharField(default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='pincode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdetails',
            name='state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
