# Generated by Django 2.1.15 on 2020-07-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0018_auto_20200714_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
