# Generated by Django 2.1.15 on 2020-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0019_auto_20200714_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='interests_count',
            field=models.IntegerField(default=0),
        ),
    ]
