# Generated by Django 2.1.15 on 2020-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0020_ticketdetails_interests_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagMaster',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=50)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hashtag_master',
            },
        ),
        migrations.CreateModel(
            name='TicketHashtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('hashtag', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
                ('dateupdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_hashtag',
            },
        ),
    ]
