# Generated by Django 2.1.15 on 2020-07-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0021_hashtagmaster_tickethashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetails',
            name='hashtag',
        ),
    ]
