# Generated by Django 2.1.15 on 2020-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0022_remove_ticketdetails_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='ticket_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
