# Generated by Django 2.1.15 on 2020-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allInterests',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TicketId', models.CharField(max_length=100)),
                ('UserId', models.CharField(max_length=100)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
