# Generated by Django 2.1.15 on 2020-07-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allinterests',
            old_name='DateUpdated',
            new_name='dateupdated',
        ),
        migrations.RenameField(
            model_name='allinterests',
            old_name='Id',
            new_name='intid',
        ),
        migrations.RenameField(
            model_name='allinterests',
            old_name='TicketId',
            new_name='ticket_id',
        ),
        migrations.RenameField(
            model_name='allinterests',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='allinterests',
            table='allinterests',
        ),
    ]
