# Generated by Django 2.1.15 on 2020-07-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='CommentText',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='UserId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
