# Generated by Django 2.1.15 on 2020-07-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapi', '0002_auto_20200709_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='AllComments',
        ),
        migrations.RenameField(
            model_name='allcomments',
            old_name='CommentId',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='allcomments',
            old_name='CommentText',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='allcomments',
            old_name='DateUpdated',
            new_name='dateupdated',
        ),
        migrations.RenameField(
            model_name='allcomments',
            old_name='TicketId',
            new_name='ticket_id',
        ),
        migrations.RenameField(
            model_name='allcomments',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='allcomments',
            table='allcomments',
        ),
    ]
