# Generated by Django 2.1.15 on 2020-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapi', '0004_auto_20200720_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcomments',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
