# Generated by Django 2.1.15 on 2020-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('preference', models.CharField(max_length=30)),
                ('profile_type', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=25)),
                ('state', models.CharField(blank=True, default='', max_length=25)),
                ('country', models.CharField(blank=True, default='India', max_length=25)),
                ('subscription_type', models.CharField(blank=True, default='Free', max_length=20)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
