# Generated by Django 2.1.15 on 2020-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0003_remove_userprofile_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
