# Generated by Django 2.1.15 on 2020-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0004_auto_20200713_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_of_tickets_posted',
            field=models.IntegerField(default=0),
        ),
    ]
