# Generated by Django 2.1.15 on 2020-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0005_userprofile_no_of_tickets_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/profile_picture/%Y/%m/%d'),
        ),
    ]
