# Generated by Django 2.1.15 on 2020-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0006_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='documents/profile_picture/%Y/%m/%d'),
        ),
    ]
